FROM mcr.microsoft.com/vscode/devcontainers/cpp:0-ubuntu-22.04

# Install additional packages sudo apt-get update && sudo apt-get install -y build-essential
RUN sudo apt-get update && \
    sudo apt-get install -y build-essential ninja-build clang-tidy clang-format